---
title: "Mentoring with Thomas"
output: html_notebook
---


This is a note that I make from conversation with Thomas, an executive director 
at Amgen with 20+ years experience in biopharmaceutical industry.

## September 2020

## August 2020

  Questions I'll ask this month
  
    a. Since trial is important, how do I pick up? From Ph1? Ph4?
    b. Choice of therapeutic area?
    c. Which part of experience is most important when doing trials?

  Ended up without asking such questions
  
  The point Thomas made: 
  
    1. Doing science is more important than just methodology research, therefore
    Berry Consultants are not as important in industry as they appear to be in
    Amgen.
    2. Innovative trials are interesting, but from operational perspective, sometimes
    they may not be welcomed.
    3. He thinks I have gained enough experience in D&I. Other skills can be learned
    from real problem, and it's good time to shift to clinical trials. 



## July 2020

  Question I asked: What is good for career development? Is clinical trial experience more important than design itself?
  
  Thomas gave a 3-dimensional viewpoint
  
    a. Disease area (e.g., Oncology, inflammation, cadiovascular)
    b. Drug development 
    c. Statistical design, conduct, DMC, filing 
  
  If I want to be more competitive in the job market, I need to experience lots trial aspects. He talked about the evolvement of Design and Innovation within Amgen. I begin to think my job may not be as important as it appears if I decide to pursue external opportunities.  

## June 2020
  Mentoring is
  
  a. generally confidential
  b. about career development
  
  Advice from Thomas
  
  + Don't think your effort will pay you back; Always think about yourself
  + hard work does not guarantee your success, learn to sell yourself
  + understand what makes you happy at work
  